Resources:
    webserverPublicIP:
        Value: !Sub ${webserver.PublicIp}
    SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Security grop blahblahblah
            SecurityGroupIngress:
                -
                    IpProtocol: tcp
                    CidrIp: 0.0.0.0/0
                    FromPort: 80
                    ToPort: 80
    webserver:
        Type: "AWS::EC2::Instance"
        Metadata: 
            AWS::CloudFormation:::Init:
                config:
                    Packages:
                        yum:
                            httpd: []
                            
                    services:
                        sysvinit:
                            httpd:
                                enabled: true
                                ensureRunning: true
        Properties:
            ImageId: "ami-e2adf99e"
            InstanceType: m4.large
            SecurityGroups:
                - !Ref SecurityGroup
            UserData: 
                Fn::Base64:
                    !Sub | 
                    #!/bin/bash -xe
                    yum install -y aws-cfn-bootstrap
                    /opt/bin/aws/cfn-init -s ${AWS::StackId} -r webserver -
                    
                